######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 27 15:02:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += main.hh ChatDialog.hh NetSocket.hh
SOURCES += main.cc ChatDialog.cc NetSocket.cc

CONFIG-=app_bundle
